### PR TITLE
Change order of annotations

### PR DESCRIPTION
**Pull request by yuyu2172**

### CODE REVIEW

**Comment by knorth55** [comment]
You do not need to change the order.
I follow `bbox, mask, label, score` order.

**Comment by yuyu2172** [comment]
https://github.com/knorth55/chainer-fcis/blob/master/fcis/models/fcis_resnet101.py#L249

**Comment by knorth55** [comment]
actually i decide to use the order in #8

**Comment by yuyu2172** [comment]
Can you change it?
It does not make sense to mix up multiple conventions.

**Comment by knorth55** [comment]
I will change all the others to follow the order, so please wait.

**Comment by knorth55** [comment]
I updated master branch to follow the order.

**Comment by yuyu2172** [comment]
ok

**Pull request closed without merging**
