### PR TITLE
add coco_instance_segmentation_dataset

### PR DESCRIPTION
**Pull request by yuyu2172**
```python
from fcis.utils import visualize_mask
from fcis.datasets.coco_instance_segmentation_dataset import COCOInstanceSegmentationDataset
from fcis.datasets.coco_utils import coco_instance_segmentation_label_names
import numpy as np
import matplotlib.pyplot as plt


dataset = COCOInstanceSegmentationDataset(split='val')
img, bbox, label, mask = dataset[1]

y_min, x_min, y_max, x_max = bbox[0].astype(np.int32)
crop_mask = list()
for i in range(len(mask)):
    y_min, x_min, y_max, x_max = bbox[i].astype(np.int32)
    crop_mask.append(mask[i, y_min:y_max, x_min:x_max].astype(np.float32))

scores = np.ones(len(label))
img = img.transpose(1, 2, 0)
visualize_mask(img, label, crop_mask, bbox, scores, coco_instance_segmentation_label_names, 0.5)
plt.show()
```

figure_1

### CODE REVIEW

**Comment by knorth55** [comment]
Thank you for your contribution!

**Comment by yuyu2172** [comment]
I feel that `mask` should not be `(N, H, W)`, but `[(H_1, W_1), ..., (H_N, W_N)]`.
This is because instance segmentation algorithms always output `[(H_1, W_1), ..., (H_N, W_N)]` before `(N, H, W)`.
Don't you think so?

**Comment by knorth55** [comment]
> This is because instance segmentation algorithms always output [(H_1, W_1), ..., (H_N, W_N)] before (N, H, W).

`output` is network output? or which one do you mean?

**Comment by yuyu2172** [comment]
Yeah.
Am I wrong?

If network can predict it without ever converting data to NHW, list representation should be used.

Please correct me if I am wrong.
I haven't really looked into functions like mask voting.

**Comment by knorth55** [comment]
actually mask prediction output is `(R, C, H, W)` `cupy` array formated, and all the masks have same `H` and `W` because it is formated in `psroi_pooling_2d`.
In `coco` demo case, I set `group_size` as `7`, so mask output shape is `(R, C, 7, 7)`.

**Comment by knorth55** [comment]
But as dataset class, each mask has each own shape, and we can resize it in other functions.

**Comment by yuyu2172** [comment]
>In coco demo case, I set group_size as 7, so mask output shape is (R, C, 7, 7).
I know. You resize the mask to `(R, C, 7, 7)` from the list `[(H_1, W_1), ... (H_R, W_R)]`.
https://github.com/yuyu2172/chainer-fcis/blob/master/fcis/mask.py#L77
But, `mask_voting` be changed to return `[(H_1, W_1), ..., (H_R, W_R)]`.
Since, (7, 7) is arbitrarily selected, the list representation looks more general and better.
 
> But as dataset class, each mask has each own shape, and we can resize it in other functions.

It is better to only have one data representation if possible.

Anyway, this is just a suggestion.
Feel free to work as you like. I think it is ok to move on with `(R, H, W)`. If so, just merge this PR.

**Comment by yuyu2172** [comment]
> But as dataset class, each mask has each own shape, and we can resize it in other functions.

Are you saying that `[(H_1, W_1) ..., (H_R, W_R)]` is better?

**Comment by knorth55** [comment]
Sorry to confuse you.
Now i think that list is better cause all masks have the same shape.
Thank you for your comment.

**Comment by yuyu2172** [comment]
```python
dataset = COCOInstanceSegmentationDataset(split='val')
img, bbox, label, mask = dataset[1]
scores = np.ones(len(label))
mask = [m.astype(np.float32) for m in mask]
img = img.transpose(1, 2, 0)
visualize_mask(img, label, mask, bbox, scores, coco_instance_segmentation_label_names, 0.5)
plt.show()

```

**Comment by yuyu2172** [comment]
This can be merged.

**Pull request merged**
